apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-odd
  # these labels can be applied automatically 
  # from the labels in the pod template if not set
  labels:
    app: redis
    role: odd
    tier: backend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically 
  # from the labels in the pod template if not set
  # selector:
  #   app: guestbook
  #   role: odd
  #   tier: backend
  template:
    metadata:
      labels:
        app: redis
        role: odd
        tier: backend
    spec:
      containers:
      - name: odd
        image: gcr.io/google_containers/redis:e2e  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
