apiVersion: v1
kind: Service
metadata:
  name: redis-odd
  labels:
    app: redis
    role: odd
    tier: backend
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: odd
    tier: backend
