apiVersion: v1
kind: Service
metadata:
  name: futz-server
  labels:
    app: talamasca
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: talamasca
    tier: frontend
